version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: flaskuser
      MYSQL_PASSWORD: flaskpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    image: python:3.12.2
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - backend
    command: bash -c "make start"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URI: mysql+pymysql://my_flaskuser:my_flaskpassword@db/my_flaskdb
